### ISSUE TITLE
TGA Image Convert Bug Orientation

### ISSUE THREAD

**Issue by TemKaSD** [ImageMagick/ImageMagick6#206] opened 2022-12-25 11:16 UTC
### ImageMagick version

6.9.12-70

### Operating system

Linux

### Operating system, version and so on

ubuntu 22.04

### Description

Hello. I have TGA image:

![image](https://user-images.githubusercontent.com/6318282/209465838-acffed08-b094-4814-84a8-8a9e9c1aceab.png)

convert to JPG:

![image](https://user-images.githubusercontent.com/6318282/209465844-3a006a6f-71bd-435b-a34b-aab5e498e8f8.png)

ImageMagick 6.9.10-23 - OK
ImageMagick 6.9.10-28 - OK
ImageMagick 6.9.10-38 - OK
ImageMagick 6.9.10-48 - OK
ImageMagick 6.9.10-58 - OK
ImageMagick 6.9.10-68 - OK
ImageMagick 6.9.10-74 - OK

ImageMagick 6.9.10-75 - BAD
ImageMagick 6.9.10-77 - BAD
ImageMagick 6.9.10-78 - BAD
ImageMagick 6.9.12-70 - BAD
ImageMagick 7.1.0-55 - BAD

Bug this code: https://github.com/ImageMagick/ImageMagick6/commit/3e322a80300f271ea9074b74110d74de4bb48fd6#diff-0b94a1b7cf3d0fcd97556cd1451faa7e7cdb1f6d9bd44b5c8b04883929bab6f8L426

### Steps to Reproduce

convert file.tga file.png

### Images

[842974301_war3mapPreview.zip](https://github.com/ImageMagick/ImageMagick6/files/10299806/842974301_war3mapPreview.zip)

**Comment by dlemstra** [comment] 2022-12-25 22:05
Duplicate of https://github.com/ImageMagick/ImageMagick/issues/5906

**Closed by dlemstra** 2022-12-25 22:05 UTC
